### ISSUE TITLE
Allow --geometry option for launching at a different size.

### ISSUE THREAD

**Issue by ryanpcmcquen** [lahwaacz/tinyterm#5]
Although I don't mind resizing/going fullscreen, it would be really cool if I could launch tinyterm with something like:

```tinyterm --geometry=140x40```

Or in the spirit of simplicity, maybe you could just have a ```tinyterm --medium``` that was a little bigger, the default seems really tiny on higher-res screens.

**Comment by lahwaacz** [comment]
This can be solved by configuring the window manager to manage the size of windows. See for example [Openbox#Window snapping](https://wiki.archlinux.org/index.php/Openbox#Window_snapping) or even use a [tiling window manager](https://en.wikipedia.org/wiki/Tiling_window_manager).

**Comment by ryanpcmcquen** [comment]
Thanks! I ended up forking the project and adding it to the config.h.
